FROM node:18-alpine as build

# Add a work directory
WORKDIR /app

# Install dependencies
COPY package*.json /app
RUN yarn

# Copy app files
COPY . /app

# Set startup
RUN yarn build

FROM nginx:latest

# Copy the built React app to Nginx's web server directory
COPY --from=build /app/dist /usr/share/nginx/html

# Copy custom nginx configuration file
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Command to run nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]