version: "3.8"

services:
  cache:
    container_name: reviewed_app_cache
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
    - ./cache/d–∞ta:/root/redis
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  backend:
    container_name: reviewed_app_backend
    image: reviewed_app_backend
    build: ./backend
    volumes:
      - ./backend/src:/app/src
      - ./backend/alembic:/app/alembic
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - cache
      - db

  frontend:
    container_name: reviewed_app_frontend
    image: reviewed_app_frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/tailwind.config.cjs:/app/tailwind.config.cjs
    ports:
      - "5173:5173"
    depends_on:
      - cache
      - backend

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
