version: "3.8"

services:
  frontend:
    container_name: reviewed_app_frontend
    image: reviewed_app_frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/tailwind.config.cjs:/app/tailwind.config.cjs
    ports:
      - "5173:5173"