version: "3.8"

services:
  app:
    container_name: reviewed_app
    image: reviewed_app
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/tailwind.config.cjs:/app/tailwind.config.cjs
    ports:
      - 5173:5173

