"""Remove not null constraints from affiliation and doi

Revision ID: 3f2311e9cad7
Revises: e15d1805bb9f
Create Date: 2023-11-30 18:36:34.323561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2311e9cad7'
down_revision: Union[str, None] = 'e15d1805bb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'affiliation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('publication', 'doi',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication', 'doi',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('author', 'affiliation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
