"""Ensure cascade deletes

Revision ID: 405f6b14ade3
Revises: 2351f3e17514
Create Date: 2023-12-15 12:47:00.464815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405f6b14ade3'
down_revision: Union[str, None] = '2351f3e17514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_search_id_fkey', 'author', type_='foreignkey')
    op.create_foreign_key(None, 'author', 'search', ['search_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('publication_author_id_fkey', 'publication', type_='foreignkey')
    op.create_foreign_key(None, 'publication', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('search_user_id_fkey', 'search', type_='foreignkey')
    op.create_foreign_key(None, 'search', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_session_user_id_fkey', 'user_session', type_='foreignkey')
    op.create_foreign_key(None, 'user_session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_session', type_='foreignkey')
    op.create_foreign_key('user_session_user_id_fkey', 'user_session', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'search', type_='foreignkey')
    op.create_foreign_key('search_user_id_fkey', 'search', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'publication', type_='foreignkey')
    op.create_foreign_key('publication_author_id_fkey', 'publication', 'author', ['author_id'], ['id'])
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.create_foreign_key('author_search_id_fkey', 'author', 'search', ['search_id'], ['id'])
    # ### end Alembic commands ###
