"""Set fields to null

Revision ID: 8d2ef0372127
Revises: 8689a170d3be
Create Date: 2023-12-14 17:22:41.123472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2ef0372127'
down_revision: Union[str, None] = '8689a170d3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'search_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'search_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
