"""Change type of field value to array

Revision ID: 95be21d41ba5
Revises: 3f2311e9cad7
Create Date: 2023-12-02 15:53:29.106915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95be21d41ba5'
down_revision: Union[str, None] = '3f2311e9cad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('venues', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('publication', 'venue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('venue', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('publication', 'venues')
    # ### end Alembic commands ###
